### ISSUE TITLE
Closing tab with 3 or more tabs bug

### ISSUE THREAD

**Issue by mat414** [node-projects/dock-spawn-ts#40] opened 2020-11-20 07:38 UTC
Trying to close a panel with at least 3 tabs causes the panel to not actually be removed. This causes several odd issues such as the panel to be closed "x" button remaining in place, thus disallowing removal of other tabs. To recreate, open IDE demo and dock infovis dock tree visualizer into outline/solution explorer panel area. Then, press the close button on the now docked tree visualizer tab. This leads me to suspect the issue is in the else block of the DockLayoutEngine close function.

```
else {
    // the node to be removed has 2 or more other siblings. So it is safe to continue
    // using the parent composite container.
    parentNode.performLayout(false);
    if (activetabClosed) {
        let nextActiveSibling = parentNode.children[Math.max(0, siblingIndex - 1)];
        if (nextActiveSibling != null)
            parentNode.container.setActiveChild(nextActiveSibling.container);
    }
 }`

**Comment by jogibear9988** [comment] 2020-11-20 08:03
could not reproduce
https://drive.google.com/file/d/1YhZKamcexgLE4mcNGfJ6ly1bf9GAD8F9/view

**Comment by jogibear9988** [comment] 2020-11-20 08:04
![Uploading https___node-projects.github.io_dock-spawn-ts_page_demo_ide_demo.html.gif…]()

**Comment by jogibear9988** [comment] 2020-11-20 08:04
![https___node-projects github io_dock-spawn-ts_page_demo_ide_demo html](https://user-images.githubusercontent.com/364896/99775316-642b5f80-2b0f-11eb-86bd-e3238c060abd.gif)

**Comment by mat414** [comment] 2020-11-20 17:42
Hmmm. Tested this with Firefox 83 (64 bit) and Chrome 87.0.4280.66. Here is a gyazo GIF of me trying it with chrome debugger open. If I go into the inspector the div id="infovis" still exists and the errors are from attempting to remove it again.
[https://i.gyazo.com/fbd8d194082cf366d8bd1aa6f056be55.mp4](url)

**Comment by jogibear9988** [comment] 2020-11-20 20:47
I tryed Chrom 86, Chrome Canary, Firefox... In all browsers I get no error in the console.
Maybe try a realod wich clearing the cache?

**Comment by mat414** [comment] 2020-11-20 21:21
Tried clearing cache as well as trying it on a different computer that has never visited the site. Same issue occurs each time. I'll try to look into it a bit more. Perhaps I'll try with Chrome 86 specifically.

**Comment by jogibear9988** [comment] 2020-11-20 22:15
i also tried chrome canary, and I get no error

**Comment by mat414** [comment] 2020-11-21 03:36
Tried canary too, but I still have the same problem. It is a bit of a hack, but I managed to create a workaround and remove the tab by treating tab pages like document tab pages. I.E The TabPage destroy function now looks like this.
```
destroy() {
        this.handle.destroy();
        if (this.container instanceof PanelContainer) {
            let panel = this.container;
            delete panel.onTitleChanged;
        }
        if (this.host.dockManager.activePanel == this.panel)
            this.host.dockManager.activePanel = null;
        this.container.tabPage = null;

        Utils.removeNode(this.container.elementPanel);
    }
```
Are you sure the version you're testing is the same as the master branch? Perhaps you could point me to where in the code the tabs panel-base element is actually meant to be removed from the DOM.

Thanks.

**Comment by jogibear9988** [comment] 2020-11-21 06:56
I don't know why you have those bugs, and I do not have them.
Do you also have the Bugs on the Online Version?
I tested Online.
Maybe I forgot to pull? Mhmm, but now I merged the last pull and build again, and it still works. But maybe also the last pull fixed smth. Maybe you take a look again

**Comment by jogibear9988** [comment] 2020-11-21 07:15
I thought your bug are the Exceptions (wich I do not have).
But for me the content also stays in the DOM.
I'll look why this was there, ane how I will fix this.
In the project where I use it, it's removed. Need to look what I do different.

**Comment by mat414** [comment] 2020-11-21 17:26
Yea so the errors in the console appear because the element stays in the DOM. For me, when it stays in the DOM, the close button of the element that you try to remove remains in place. That is why, even though it appears I am clicking the 'X' button for the next tab, it is actually clicking the 'X' button for the tab I already deleted thus causing the console error.

**Comment by mat414** [comment] 2020-12-07 17:29
Any news on this topic?

**Closed** 2020-12-12 23:39 UTC

**Comment by jogibear9988** [comment] 2020-12-21 07:18
@mat414 does it work now?
